### PR TITLE
Reconnect without deleting message buffers

### LINKED ISSUE #256: Buffer gets killed if connection flickers
Hi there,

If my connection drops for a few seconds, the slack client is forced to reconnect (which happens automatically). By itself that's perfectly fine, but the problem is that it also kills currently open chat buffers, which can cause the user to lose work. Several times already I've lost a message I was writing because the buffer disappeared under my fingers.

Is there a way to prevent this?

### PR DESCRIPTION
**Pull request by yuya373**
close #256 

use `reconnect_url`. when it is expired, pulls messages from server and redisplay.

### CODE REVIEW

**Comment by emacswatcher** [comment]
Every 'slack-start' still deletes all existing buffers.

**Comment by yuya373** [comment]
This is intentional. 
Reconnection happens automatically when connection is closed. 

2018/08/26 0:43、emacswatcher <notifications@github.com>のメール:

**Comment by emacswatcher** [comment]
Ah! I see. 

However, when "reconnect limit reached..." forces a reconnect, is it still necessary to delete and start over?

**Comment by yuya373** [comment]
> However, when "reconnect limit reached..." forces a 'slack-start', is it still necessary to delete and start over?

This is true and data can not be saved.
Reconnection happens up to 360 times every 10 seconds and "360 times" is not configurable yet.

**Comment by emacswatcher** [comment]
I understand. Thank you for your replies.

**Pull request merged**
