### PR TITLE
Use Linewise User Interface for Slack rooms

### PR DESCRIPTION
**Pull request by ryuslash**
Hi,

I ran into your project through [this](https://www.reddit.com/r/emacs/comments/3uqork/someone_is_working_on_another_slack_client/) reddit thread. I've been wanting to try and write an Emacs Slack client for awhile and just felt like I could get around to it when I read that thread. So I immediately tried out your client.

It was a bit of a challenge. First trying to find out where to find the client id and secret and the token, which would have been much easier if I'd paid more attention to the README. And then how to send a message. `M-x slack-message-send RET My message C-j` is not exactly my idea of a frictionless workflow. It was also a bit strange to find that `RET` in the minibuffer added a newline instead of sending the message.

Anyway, I thought that it would be great to have a prompt at the bottom of the room buffer where messages could be typed and sending was as easy as pressing `RET`, much like ERC, Circe, jabber.el and probably others. I also thought that Circe's `lui.el` implemented much of this, so I wanted to try and hack together emacs-slack and `lui.el`. Here I present to you my first draft. I've been testing it with my work Slack account a bit and I like the way it works. Now I would appreciate your opinion on this.

Using `lui.el` takes care of a few things. It allows us to easily add a prompt and send messages by using that prompt, takes care of showing the messages before the prompt (and keeping them read-only) and shows notifications in the modeline, to name a few.

Of course it's a bit weird that this also introduces a dependency on Circe, but perhaps if you like it and want to develop on this further, we could ask the Circe people if it is possible to split the `lui.el` into its own project.

In any case, great work on this project, I'm very happy that I ran into it. Thanks in advance for your time.

Cheers,

Tom

### CODE REVIEW

**Comment by yuya373** [comment]
Hi 
Thank you for trying and pull request.
I tried your branch,  I like the prompt `> ` and interface too.

but `slack-buffer-update-notification` was broken,  with Warnings below.
```
Error (websocket): in callback `on-message': Wrong type argument: markerp, nil
```
After I changed `slack-buffer-update-notification`,  Warning disappears.
```
 (defun slack-buffer-update-notification (buf-name string)
   (let ((buffer (get-buffer-create buf-name)))
     (with-current-buffer buffer
-      (lui-insert text))))
+      (lui-mode)
+      (lui-insert string))))
```

Also I'm confused by few things.
First, The function below interrupt me when updating buffer with new message.
```
(defun lui-change-major-mode ()
  "Assure that the user really wants to change the major mode.
This is a good value for a buffer-local `change-major-mode-hook'."
  (when (not (y-or-n-p "Really change major mode in a Lui buffer? "))
    (error "User disallowed mode change")))
```
Is it good to use `remove-hook` with this?

Second, `lui-time-stamp` function using `format-time-string`.
I think It is more accurate to use time-stamp included with websocket payload.

**Comment by ryuslash** [comment]
Hey,

Yuya Minami <notifications@github.com> writes:

> Thank you for trying and pull request.
> I tried your branch, I like the prompt > and interface too.

I'm glad to hear that. Thank you for taking the time to try it out.

> but slack-buffer-update-notification was broken, with Warnings below.
>
> Error (websocket): in callback `on-message': Wrong type argument: markerp, nil
>
>
> After I changed slack-buffer-update-notification, Warning disappears.
>
>  (defun slack-buffer-update-notification (buf-name string)
>    (let ((buffer (get-buffer-create buf-name)))
>      (with-current-buffer buffer
> -      (lui-insert text))))
> +      (lui-mode)
> +      (lui-insert string))))

Sorry about this. As it was a quick and dirty way to get emacs-slack
working with `lui.el` I didn't thoroughly test it.

This patch isn't the way to go, I'm afraid. First off, it uses
`lui-mode`, which shouldn't be used directly. It should enable
`slack-mode` when a new buffer is created. And secondly it resets the
major mode every time the function is called on the same buffer, which
causes the problem below.

So I've pushed a change that enables `slack-mode` whenever a new buffer
is created, but doesn't call it again when updating an existing buffer.

> Also I'm confused by few things.
> First, The function below interrupt me when updating buffer with new message.
>
> (defun lui-change-major-mode ()
>   "Assure that the user really wants to change the major mode.
> This is a good value for a buffer-local `change-major-mode-hook'."
>   (when (not (y-or-n-p "Really change major mode in a Lui buffer? "))
>     (error "User disallowed mode change")))
>
>
> Is it good to use remove-hook with this?

I ran into this when I first derived `slack-mode` from `lui-mode` too. I
fixed it by only enabling the major mode when a new buffer was created,
not when a buffer was updated.

I don't think removing this hook is the best idea, I think it's better
to only enable `slack-mode` when a new buffer is created because if we
enable `slack-mode` on every update, we also run the mode's
initialization code every single time an update occurs.

The change I pushed should keep this from happening.

> Second, lui-time-stamp function using format-time-string.
> I think It is more accurate to use time-stamp included with websocket payload.

I agree, I hadn't come around to trying this yet.

I've looked at the `lui-time-stamp` function and currently it offers no
way of specifying a different time. I will see if they're open for a
change to allow us to do that, so I'll have to get back to you on that
if you don't mind.

Thank you for your feedback and I look forward to the next round :)

**Comment by yuya373** [comment]
Thank you for fixing buffer creating function and creating issues about `lui.el` in circe repository.
It would be great to pass specific time to `lui-time-stamp` function.
Anyway, I will merge this PR. Thank you very much!

**Comment by ryuslash** [comment]
Thank you for merging this. I will follow up on that `lui-time-stamp` issue and once that has been discussed and implemented I will try to create another pull request.

Today is my first official day at work with Slack in Emacs :)

**Pull request merged**
