### PR TITLE
Bind lui-time-stamp-time when inserting messages in a buffer

### PR DESCRIPTION
**Pull request by ryuslash**
Hi,

As discussed in a previous pull request I was able send a patch to the Circe maintainer that allows us to change the time stamp lui outputs when inserting a message.

This change is only available in the latest git revisions of Circe and hasn't been officially released yet. I've upped the minimum required version in the pkg file to reflect that the next version released will be required. This should be fine for Melpa right now since any Melpa version should be higher than 2.2. Anyone using Melpa Stable instead would have trouble since 2.2 isn't on there yet. This shouldn't be an issue right now since there are no tags in this project yet, so it shouldn't show up on Melpa Stable.

I removed the time stamp from the message header because I didn't see the point in showing it twice.

I also removed the setting of `lui-time-stamp-position`, since this will also affect my Circe buffers, as this isn't a buffer-local setting, nor is it set buffer-locally (this is also true for `lui-fill-type`).

Please let me know what you think.

Cheers,

Tom

### CODE REVIEW

**Comment by yuya373** [comment]
Hi!

I tried your pull request, and see `slack-buffer-replace` is weird.
This is caused by lui-time-stamp is not inserted into same minutes messages.
I wrorte a patch, but this patch is working only `lui-time-stamp-position` is right.
https://gist.github.com/yuya373/3d127c7cade6ff88f006

Is is better way to set `lui-time-stamp-position` to right buffer locally?

**Comment by ryuslash** [comment]
Thank you for your feedback!

I'll have a better look later when I have some more time. For now I just wanted to say that I think binding `lui-time-stamp-position` is not what we should do because it is a user setting and I personally don't like it when packages I install start dictating my settings.

Sorry for the rushed comment.

**Comment by ryuslash** [comment]
Hey,

Sorry for taking so long on getting back to this, but today I finally buckled down and tried my darndest to fix this.

The new code feels like a bunch terrible hacks, so I wouldn't blame you if you don't want to merge it as-is. I think I may make the Circe developers cry with some of the internals I butcher in this code. I also wouldn't be surprised if I overlooked some other function that has now broken.

However, it seems to work on my machine. I've tried it with both `lui-time-stamp-position` set to `right` as well as `right-margin`. To test with `right-margin`, the right margin should be given a proper size:

```elisp
(add-hook 'lui-mode-hook (lambda () (setq right-margin-width 7)))
```

Please let me know what you think.

Perhaps one way of making this less hackish is discussing a feature for Circe (specifically lui.el) to edit lines. If you think this is a good idea I will contact the Circe people about this, unless you want to do it yourself.

**Comment by yuya373** [comment]
Hi
thank you for your fix, `slack-buffer-replace` is now behave correctly.
I tried `slack-room-update-messages`,  timestamp disappear.

1. I wrote message and timestamp appear correctly.



2. I execute `slack-room-update-messages`, timestamp disappear.


I feel tired to struggle with lui.el, I hope lui.el is splitted from circe, and have more handy api.

**Comment by ryuslash** [comment]
Thanks for trying it out again, I hadn't considered `slack-room-update-messages`.

I know how you feel, but I can understand it too. Slack works a lot like IRC in some ways, but in others also doesn't (editing messages, retrieving remotely stored history, adding reactions, etc.) and lui.el was obviously only made with IRC in mind (or perhaps other more IRC-like protocols as well). I had hoped to move on to message formatting now, but it seems I'm not done with the timestamp yet.

I'll see what I can do, and I'll open an issue with Circe to discuss adding any `lui-replace`, `lui-delete` or `lui-edit` functions.

Are there any other functions/hacks that would fit better in lui than emacs-slack? I can imagine if the "load more" functionality would also be a good addition to lui.

**Comment by ryuslash** [comment]
I can't reproduce your issue with `slack-room-update-messages`, I tried saying something to slackbot and in our #random channel and calling `slack-room-update-message` after either keeps my times tamps just stay where they are.

I've tried this with both my usual configuration (where `lui-time-stamp-position` is `right-margin`) and with `emacs -Q`, in which case `lui-time-stamp-position` is `right`.

**Comment by yuya373** [comment]
hmm...
also, In my environment, when I open room lui-time-stamp string is not shown with messages, just shown at top of the buffer with "(load more message)".
How about this?

> I'll see what I can do, and I'll open an issue with Circe to discuss adding any lui-replace, lui-delete or lui-edit functions.

> Are there any other functions/hacks that would fit better in lui than emacs-slack? I can imagine if the "load more" functionality would also be a good addition to lui.

that is great. 
In lui-mode deleting and replacing message need to know lui internal mechanism, I want CRUD interface at the beginning. (C is already `lui-insert`)

**Comment by ryuslash** [comment]
> hmm...
also, In my environment, when I open room lui-time-stamp string is not shown with messages, just shown at top of the buffer with "(load more message)".
How about this?

I don't think I have this problem, I see the time stamps wherever they need to be. It's not incidentally that all the messages you see just have the same time stamp, is it? By default it's only shown when the time stamp changes (see `lui-time-stamp-only-when-changed-p`).

> In lui-mode deleting and replacing message need to know lui internal mechanism, I want CRUD interface at the beginning. (C is already lui-insert)

Yeah I'm discussing implementing replace and delete functions in jorgenschaefer/circe#241 in case you want to follow along or provide additional input.

**Comment by yuya373** [comment]
Oh It is my mistake. lui.elc is old, though lui.el is up to date.
now your time stamp feature working! :tada: 
here some small fixes pls.

slack-message-formatter.el
``` 
@@ -83,3 +83,2 @@
-      (let ((name (slack-message-sender-name m))
-            (time (slack-message-time-to-string ts)))
-        (format "%s %s" name time))))
+      (let ((name (slack-message-sender-name m)))
+        name)))
```
delete timestamp from header for bot messages.


slack-room.el
```
@@ -162 +162 @@
-                                     'oldest))
+                                     'slack-last-ts))
```
delete "(load more message) [lui-time-stamp]".
there would be better way for this.

> Yeah I'm discussing implementing replace and delete functions in jorgenschaefer/circe#241 in case you want to follow along or provide additional input.

I will catch up later, thanks!

**Comment by ryuslash** [comment]
> Oh It is my mistake. lui.elc is old, though lui.el is up to date.
now your time stamp feature working! :tada:

Awesome! :tada:

> here some small fixes pls.

Done. I've simplified the first even more (I hope not too much), since there was no more need for the `ts` slot. The second one I wasn't entirely sure of why `slack-last-ts` is better than `oldest`, so I just copied what you said into the commit message.

**Comment by yuya373** [comment]
thanks!  merge this.

> The second one I wasn't entirely sure of why slack-last-ts is better than oldest, so I just copied what you said into the commit message.

because, I want to delete lui-timestamp with "(load more message)".

**Comment by ryuslash** [comment]
Thanks for merging :)

**Pull request merged**
