### PR TITLE
on buffer update, create buffer if it doesn't yet exist

### PR DESCRIPTION
**Pull request by event**
If one uses osd notifications she wouldn't ever find out if she was notified on channel if buffer is not open. This patch fixes it.

### CODE REVIEW

**Comment by yuya373** [comment]
Thank you very much for contribution!
I tried this patch, have a few questions.

- what is osd notifications?
- why osd notification needs buffer is opened?
- osd notification users need buffer opened or buffer created(buried, not in current window)?

**Comment by event** [comment]
Hi, 
OSD (On-Screen Display) notifications are small short-living windows appearing usually on the right top side of the screen (here is ubuntu unitiy variant of those https://www.youtube.com/watch?v=fOHQHkw82eg). alert library style notificattions is used to enable those.
OSD notification don't need buffer opened. However if buffer is not opened and user is away she would never know if she was notified.
I think buffer needs to be created.

**Comment by yuya373** [comment]
Thanks for description.
I feel very annoying buffer popup when new message received while focusing emacs.
Is there stacking notification list like below in other notification system?


wscreenshot 2016-11-04 at 19 02 31

In English, two messages from Emacs on top right corner.

**Comment by event** [comment]
I believe stacking is up to notification daemon implementation. Unity doesn't do it.
 
This pull request is intended to create a buffer when user is notified. Otherwise if user is away she won't know if she was notified.

**Comment by yuya373** [comment]
Ok, I want something like `(defcustom slack-foo-bar nil)`.
when this variable is true, call `slack-room-make-buffer-with-room` when notified.

**Comment by event** [comment]
@yuya373  it's done now.

**Comment by event** [comment]
@yuya373 HI, I improved it a bit so it doesn't bring new buffers to front automatically and works faster as well

**Comment by yuya373** [comment]
thanks!

**Pull request merged**
