### PR TITLE
add modeline unread count

### LINKED ISSUE #177: [feature-request] Modeline notification similar to mu4e-alert
I would love to have a modeline notification that shows how many slack unread slack notifications I have. Sometimes I miss a notification, and it would be nice to see that I have unread slack message in my modeline.

### PR DESCRIPTION
**Pull request by yuya373**
close #177 

add custom variables
- `slack-modeline-formatter` 
  - function takes argument like `'((team-name . unread-count) ... )`
- `slack-modeline-count-only-subscribed-channel`
  - default `t`. if `nil` count all channel's unread-count.

add team configurations
- `modeline-enabled`
  - default `nil`. set this `t` if you want to show unread-count at modeline.
- `modeline-name`
  - default `nil` name displayed at modeline. if nil, use team name from slack server.

### CODE REVIEW

**Comment by Malabarba** [comment]
Hi there. As usual, thanks for this package.

Has this feature replaced the previous system for modeline notifications (which was based on tracking.el)?
With tracking.el I could see per-channel notifications, and I had commands to cycle through the buffers, but a recent update removed all that. Is there a way to get these two funcionalities back with the new feature?

**Comment by Malabarba** [comment]
Wait, now I'm not sure anymore.
It seems I'm still getting the `tracking.el` notifications, but not always. Also, sometimes I get messages displayed twice on the buffer. It's very occasional, but I noticed that the few cases when a buffer gets tracked by `tracking.el` coincide with the cases when the message is displayed in double.

I also occasionally get the following warning on the `*Warnings*` buffer:

    Error (websocket): in callback `on-message': Args out of range: "", 0


Would you like me to open a bug report with all this?

**Comment by Malabarba** [comment]
More info. It seems like a conversation only gets tracked after I've visited it once.

**Comment by yuya373** [comment]
@Malabarba 
> Also, sometimes I get messages displayed twice on the buffer.

fixed this in d2aa8bdc85925101fb10688e00711c1daf73117e

> but I noticed that the few cases when a buffer gets tracked by tracking.el coincide with the cases when the message is displayed in double.

fixed this in b1e360ece4751cbcd1ec57343e391291fd890090

thanks for reporting. but I don't know about `Args out of range` error.
`(setq websocket-callback-debug-on-error t)` to get stack trace and it helps a lot.

**Pull request merged**
