### PR TITLE
support the `:display-profile-image` argument in `register-team`

### PR DESCRIPTION
**Pull request by matthew-piziak**
I noticed that `:display-profile-image` wasn't supported. Was that unintentional? If so, here is a PR to enable it. I've tested it locally and it seems to work for me.

### CODE REVIEW

**Comment by yuya373** [comment]
According to [this](https://github.com/yuya373/emacs-slack/commit/76e73fb46fc1431f1759a97fe92bac54f5f457b3) commit, I want to remove `display-profile-image`.
I want to control whether to display the profile image using [`slack-render-image-p`](https://github.com/yuya373/emacs-slack/blob/master/slack-image.el#L44).

**Comment by matthew-piziak** [comment]
So you want those options to be coupled? Will it be possible to view images in messages, but keep profile pictures hidden?

**Comment by yuya373** [comment]
> So you want those options to be coupled? 

yes
> Will it be possible to view images in messages, but keep profile pictures hidden?

no

**Comment by matthew-piziak** [comment]
Fair enough! Thanks @yuya373, stay safe.

**Pull request closed without merging**
